### ISSUE TITLE
About subject

### ISSUE THREAD

**Issue by lfv89** [GabrielaGuedes/tic-tac-toe-refactor#2]
https://github.com/GabrielaGuedes/tic-tac-toe-refactor/blob/a13b32e51b93c1b20152fef3b2994001877be9bf/spec/board_spec.rb#L11

when is necessary to reference `subject` directly, a good practice is to define the `subject` with a name, something like:

```
subject(:board) { described_class.new }
```

then it can be referenced as:

```
expect(board.available_tile?(tile).to eq(true)
```

**Comment by GabrielaGuedes** [comment]
I have implemented these changes, so I will close this issue
